Event
purplenoodlesoop/flutter_effector pull request #3
Opened 2021-06-26 09:58 UTC by unger1984

Переделал в один тип Event вместо двух. Есть недостатки (видно в примере приходится вызывать с null если не задан тип), но думаю можно решить чуть позже

2021-06-26 10:05 UTC, mit-73 requested changes

2021-06-26 10:05 UTC, mit-73 commented on lib/src/event.dart
> +Event<T> createEvent<T>(String name) => _Event<T>(name);
nextUnitID потерял, так как createEvent не должен обязательно принимать name

2021-06-26 10:05 UTC, mit-73 commented on lib/src/event.dart
> +Event<T> createEvent<T>(String name) => _Event<T>(name);
https://effector.dev/docs/api/effector/createEvent

2021-06-26 10:07 UTC, unger1984 commented on lib/src/event.dart
> +Event<T> createEvent<T>(String name) => _Event<T>(name);
не заккомитилось почему-то при мердже

2021-06-26 11:17 UTC, purplenoodlesoop commented
Честно говоря, я бы лучше имел два конструктора Event и две привзяки, чем иметь:

Лишний параметр в привязке, `(state, {message}) => state + 1` вместо `(state) => state + 1`, даже там, где он не нужен
Необходимость создания лямбды вместо callable instance и передачи null, `onPressed: () => increment(null)` вместо `onPressed: increment`

Я подумаю как оставить существующий API, но не плодить сущности. Решением вижу опциональные безымянные аргументы, но может быть проблема с попаданием на null.

2021-06-26 12:12 UTC, unger1984 commented
![Screenshot_20210626_150954_org telegram messenger](https://user-images.githubusercontent.com/1415693/123512557-c7c2d000-d690-11eb-8312-ee17b8f0e67a.jpg)
Вот что MiT предлагает для решения этой проблеммв

2021-06-26 22:06 UTC, purplenoodlesoop commented
Кажется, сохранить такой же минималистичный API не плодя сущности невозможно. 

Сделал то же самое, что в PR, но с unnamed параметрами – в UI API остался прежним, но появилась опасность нарваться на `null` и в части бизнес-логики все осталось так же некрасиво:

```dart
final updateText = createEvent<String>("update text");
final toggleUppercase = createEvent<void>("toggle uppercase");
final resetUppercase = createEvent<void>("reset uppercase");

final uppercaseStore =
    createStore(UppercaseModel(currentText: "", isUppercased: false))
        .on<String>(
          updateText,
          (state, [message]) => UppercaseModel(
            currentText: message!,
            isUppercased: state.isUppercased,
          ),
        )
        .on<void>(
          toggleUppercase,
          (state, [_]) => UppercaseModel(
            currentText: state.currentText,
            isUppercased: !state.isUppercased,
          ),
        )
        .reset(resetUppercase);
```

Исходя из этих данных, предлагаю оставить раздельные `Transform`, `Event`, `createEvent` и `on` для двух типов `Event`.

2021-06-26 22:08 UTC, unger1984 commented
Чем тебе не нравится идея MiT разделить Transform в классы - решит сразу проблему апи и не надо будет два разных типа эвентов. Учитывая что у нас еще эффекты планируются, сущьности расплодятся сильно

2021-06-26 22:21 UTC, purplenoodlesoop commented
Не совсем понимаю как будет решен вопрос с API в UI при выделении трансформов к классы, но это вопрос к @mit-73 .

2021-06-27 07:48 UTC, mit-73 commented
@unger1984 @purplenoodlesoop https://github.com/purplenoodlesoop/flutter_effector/pull/4

2021-06-27 14:43 UTC, closed without merging